//! The `rfc5280_ext_authority_key_identifier_no_key_identifier` lint
//! (RFC 5280 §4.2.1.1).
//!
//! RFC 5280 §4.2.1.1: "The keyIdentifier field of the authorityKeyIdentifier
//! extension MUST be included in all certificates generated by conforming CAs to
//! facilitate certification path construction." An AKI extension that carries
//! only `authorityCertIssuer`/`authorityCertSerialNumber` but no `keyIdentifier`
//! does not meet this requirement.
//!
//! This lint is scoped to certificates that carry an AKI extension and fails
//! when the extension has no `keyIdentifier` field.

use crate::cert::Cert;
use crate::{Applicability, Finding, Lint, RuleSource, Severity};

/// Requires a present AKI extension to carry a `keyIdentifier` field.
#[derive(Debug, Clone, Default)]
pub struct ExtAuthorityKeyIdentifierNoKeyIdentifier;

impl ExtAuthorityKeyIdentifierNoKeyIdentifier {
    /// Creates the lint.
    pub fn new() -> Self {
        ExtAuthorityKeyIdentifierNoKeyIdentifier
    }
}

impl Lint for ExtAuthorityKeyIdentifierNoKeyIdentifier {
    fn id(&self) -> &'static str {
        "rfc5280_ext_authority_key_identifier_no_key_identifier"
    }

    fn source(&self) -> RuleSource {
        RuleSource::Rfc5280
    }

    fn applies(&self, cert: &Cert) -> Applicability {
        // Scoped to certs that carry an AKI extension. Fail policy: if the
        // extension cannot be read, treat the rule as out of scope (see module
        // docs).
        match cert.authority_key_identifier() {
            Ok(Some(_)) => Applicability::Applies,
            Ok(None) | Err(_) => Applicability::NotApplicable,
        }
    }

    fn check(&self, cert: &Cert) -> Vec<Finding> {
        // `applies` guarantees an AKI extension exists. Fail policy: unreadable
        // extension means we cannot evaluate; emit nothing (see module docs).
        let aki = match cert.authority_key_identifier() {
            Ok(Some(aki)) => aki,
            Ok(None) | Err(_) => return Vec::new(),
        };

        if aki.has_key_identifier {
            Vec::new()
        } else {
            vec![Finding {
                severity: Severity::Error,
                message: "AuthorityKeyIdentifier extension is present but has no \
                          keyIdentifier field; RFC 5280 §4.2.1.1 requires it"
                    .to_string(),
            }]
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cert::Cert;

    // good.pem: a leaf with NO AKI extension — the lint is out of scope for it.
    const NO_AKI_PEM: &[u8] = b"\
-----BEGIN CERTIFICATE-----
MIIDDzCCAfegAwIBAgIBETANBgkqhkiG9w0BAQsFADAbMRkwFwYDVQQDDBBnb29k
LmV4YW1wbGUuY29tMB4XDTI2MDYwMTAwMDAwMFoXDTI3MDYwMTAwMDAwMFowGzEZ
MBcGA1UEAwwQZ29vZC5leGFtcGxlLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBAOVqsq5MvB+yyI4NRCM7AoV145FqR9bjJW1XwBHq1oOsMH7jy9JA
Dd37dxgZ6c184luYA1O3fSx0N7lWQFDo8M2ZHWtlK/EHHa7lM2A9fJbFAid6K4SQ
FKRkFckqX0RasPV8Cy0g6EaN3Wvi4RXIKeHgvSGuVW6EMCizwTAjtHurIxvcf4ZU
kkmAFItv1F+CPSmRHnrjPqfrClRpDHNXqnXtgxOjW7sb7RdFDNLo2OFlDWWF69A7
Na4OhJtoR8PJgftQAUT+U/f8HliG64dhFfLu4xWWRgVWrPkO7Cah8mCwNWvFNPR5
TQPPJiZ0pSjK8MNrZmV7iK+uJc1XuqxbWLkCAwEAAaNeMFwwCQYDVR0TBAIwADAT
BgNVHSUEDDAKBggrBgEFBQcDATAbBgNVHREEFDASghBnb29kLmV4YW1wbGUuY29t
MB0GA1UdDgQWBBQdM1O88ecxlvln0vxyCvCWfS9MEzANBgkqhkiG9w0BAQsFAAOC
AQEAjj/gfkw2Mw7TCgCGWbdc8c7HjV9OQMcm0kNC7S5baFwCgk2L3bKmzIcIZuQy
ErSSlzNCJde0PdTVTx/1bsGPKpgLF/ea15ciJZ+MPvdnOuVVIiaG1G69HLSa5E8q
v5Dv2yX1drGBJHAFiV44vx+04qyqgRRpZbLKr+2n7F3ny6syIl2OK0++RAIue4W/
hCD60KaCpZDjjnT+EQOwdIK131NH8ELTGWbTKd3meuKnNJByPHPwuzK2ybWl7B3/
hHHWDhUD3r/G9CsO500Gwq9C+2djz003D/1sgUiuv93+8HoeotnMOWRwmsDs5nDQ
f63Xm57T5UNHDT/XSK4j6q6dJw==
-----END CERTIFICATE-----
";

    // A CA cert whose AKI carries a keyIdentifier (self-issued) — passes.
    const AKI_WITH_KEYID_PEM: &[u8] = b"\
-----BEGIN CERTIFICATE-----
MIIDETCCAfmgAwIBAgIUMEVvgM5RLvNLwl0CpYQKB9Hp5vowDQYJKoZIhvcNAQEL
BQAwFzEVMBMGA1UEAwwMZ29vZC5leGFtcGxlMCAXDTI0MDEwMTAwMDAwMFoYDzIx
MjQwMTAxMDAwMDAwWjAXMRUwEwYDVQQDDAxnb29kLmV4YW1wbGUwggEiMA0GCSqG
SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCkCYfXtr44fwqCzvyGVIocEF63AushxDWf
cIkFoEmJvocMuLYjGYJYJERFkfmewjMxkpefvOxvaG3yTTKMKPbqyCy14AXdYNVu
LQBkabl6fB/RzvVgqfFGuieqtAIJAZ9wHi2dZQ8dkDDMZTkhZ6+aNGz8nfuSRu09
6p33MrM5nTnzc47lOWlVrS4BqhUVVc6QGyk4GeiDx85JEC/uiJm7XOvkJ2yuczko
H9pZRZhxfQYlek/wBLaXRxPhs+t4QiClZv9OcthSuvbwAp86kjlhg+lSD/SAzi0V
HZwl2FzuY6E6uf4VfYai5+02IIOojg/ZSlS2JYUUhJegQqq5EI6/AgMBAAGjUzBR
MB0GA1UdDgQWBBS5Z3XGfJEqJgu3cOQ2/xtFoqVIoTAfBgNVHSMEGDAWgBS5Z3XG
fJEqJgu3cOQ2/xtFoqVIoTAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA
A4IBAQBF5CJ4L9cOFgBGg+FKcrYFEl44wkxGXbsnBboHI3TmuuZFWnJigf6s0fql
jc/wc5z6VxMpyffoJka+Yyj1+rAGAi1rs7XJGNFEwvBt3t+EBS+m+oLayN6M0PyW
9M56DA4RQ94r41kBpRZ7csxGS445FdF3v/tX4wyvp3iEt9xooQJbUsVA5YWIxw7m
UJPlG7T5AvQLi6uDXdz3jINPkFXiyiY0TST9ovBEUcaEm0dflkzuxalpgBqgl/M1
2NX13Gvbs4x8q4YE/bA5hivzacVDpIdOPogqIgYANBQVlyAK81pFcXUXeobhKcOe
oWraeM6JK6PALHP6RN1XoUTQaOT5
-----END CERTIFICATE-----
";

    fn load_one(pem: &[u8]) -> Cert {
        let mut certs = Cert::from_pem(pem).expect("fixture must parse");
        certs.pop().expect("fixture must contain one cert")
    }

    #[test]
    fn not_applicable_when_aki_absent() {
        let cert = load_one(NO_AKI_PEM);
        assert_eq!(
            ExtAuthorityKeyIdentifierNoKeyIdentifier::new().applies(&cert),
            Applicability::NotApplicable
        );
    }

    #[test]
    fn applies_when_aki_present() {
        let cert = load_one(AKI_WITH_KEYID_PEM);
        assert_eq!(
            ExtAuthorityKeyIdentifierNoKeyIdentifier::new().applies(&cert),
            Applicability::Applies
        );
    }

    #[test]
    fn passes_aki_carrying_keyid() {
        let cert = load_one(AKI_WITH_KEYID_PEM);
        assert!(
            ExtAuthorityKeyIdentifierNoKeyIdentifier::new()
                .check(&cert)
                .is_empty()
        );
    }

    #[test]
    fn has_correct_id_and_source() {
        let lint = ExtAuthorityKeyIdentifierNoKeyIdentifier::new();
        assert_eq!(
            lint.id(),
            "rfc5280_ext_authority_key_identifier_no_key_identifier"
        );
        assert_eq!(lint.source(), RuleSource::Rfc5280);
    }
}
