//! Integration tests for the four broad-scoped CA/Browser Forum Baseline
//! Requirements lints (`cabf_br_validity_max_398_days`, `cabf_br_cn_in_san`,
//! `cabf_br_no_internal_names_or_reserved_ip`,
//! `cabf_br_ext_key_usage_server_auth_present`), exercised against the real
//! committed `testdata/` fixtures through the public `Cert` facade.
//!
//! # Scoping (BROAD — load-bearing)
//!
//! Every BR lint applies to EVERY non-CA leaf and is `NotApplicable` for CA
//! certs; they are NOT EKU-gated. Each fixture below is a leaf that is
//! BR-compliant EXCEPT its single intended violation, so running it over the
//! FULL `default_registry()` (14 lints) surfaces exactly one rule.
//!
//! # Fixture naming
//!
//! The reserved-name classifier treats `.example`, `.test`, `.local`,
//! `.internal`, and single-label names as internal/reserved, so the
//! BR-compliant SANs use genuinely public `*.example.com` names (TLD `com`,
//! which is not a reserved suffix). `cabf_br_internal_san.pem` deliberately adds
//! `internal.local` + `10.0.0.1` to trip the internal/reserved lint.
//!
//! # ⚠️ Time-fragility
//!
//! BR-compliant leaves use a currently-valid `<=398d` window
//! (`2026-06-01 -> 2027-06-01`); `cabf_br_validity_400_days.pem` uses
//! `2026-06-01 -> 2027-07-06`. They EXPIRE in 2027; after that
//! `hygiene_not_expired` fires on every leaf and these isolation tests fail
//! wholesale. Regenerate `testdata/` annually (see `testdata/generate.sh`).
//!
//! Conventions (`.claude/rules/rust-testing-core.md`): SIFER, nested module per
//! lint, `.unwrap()`-style result assertions.

use linter::lints::cabf_br::{
    BasicConstraintsPresent, CertificatePoliciesPresent, CertificatePoliciesReservedOid, CnInSan,
    DnsnameBadCharacterInLabel, DnsnameLabelTooLong, DnsnameUnderscoreInSld,
    DnsnameWildcardLeftOfPublicSuffix, ExtKeyUsageAnyProhibited, ExtKeyUsageServerAuthPresent,
    ExtKeyUsageServerAuthRequired, ExtraSubjectCommonNames, NoInternalNamesOrReservedIp,
    OrganizationalUnitNameProhibited, RsaModulusBitsMultipleOf8, RsaPublicExponentInRange,
    SanDnsOrIpOnly, SanPresent, SubjectContainsReservedIp, SubjectCountryNotIso,
    SubscriberBasicConstraintsPathLenProhibited, SubscriberKeyUsageCertSignProhibited,
    SubscriberKeyUsageCrlSignProhibited, ValidityMax398Days,
};
use linter::{Applicability, Cert, Lint, Severity, default_registry_with_now};

/// A reference "now" inside every currently-valid fixture window (2026-12-01 in
/// Unix seconds), used to pin the clock for full-registry runs that include the
/// hygiene source so `hygiene_not_expired` cannot trip once the real date passes
/// the fixtures' `notAfter` (these leaves expire 2027-06-01).
const TEST_NOW: i64 = 1_796_083_200;

// `include_bytes!` resolves relative to this source file
// (crates/linter/tests/cabf_br.rs); `../../../testdata` reaches the
// workspace-root `testdata/` directory.
const GOOD_PEM: &[u8] = include_bytes!("../../../testdata/good.pem");
const VALIDITY_400_PEM: &[u8] = include_bytes!("../../../testdata/cabf_br_validity_400_days.pem");
const CN_NOT_IN_SAN_PEM: &[u8] = include_bytes!("../../../testdata/cabf_br_cn_not_in_san.pem");
const INTERNAL_SAN_PEM: &[u8] = include_bytes!("../../../testdata/cabf_br_internal_san.pem");
const MISSING_SERVERAUTH_PEM: &[u8] =
    include_bytes!("../../../testdata/cabf_br_missing_serverauth.pem");
const EMPTY_SUBJECT_NO_SAN_PEM: &[u8] =
    include_bytes!("../../../testdata/rfc5280_empty_subject_no_san.pem");
const CA_BC_NOT_CRITICAL_PEM: &[u8] =
    include_bytes!("../../../testdata/rfc5280_ca_bc_not_critical.pem");

// Feature 12 depth-expansion BR fixtures (each a BR-compliant leaf EXCEPT its
// one target, modulo the three documented inherent overlaps; generated by
// testdata/generate.sh).
const DNSNAME_UNDERSCORE_PEM: &[u8] =
    include_bytes!("../../../testdata/cabf_br_dnsname_underscore.pem");
const DNSNAME_BAD_CHAR_PEM: &[u8] =
    include_bytes!("../../../testdata/cabf_br_dnsname_bad_char.pem");
const DNSNAME_LABEL_TOO_LONG_PEM: &[u8] =
    include_bytes!("../../../testdata/cabf_br_dnsname_label_too_long.pem");
const DNSNAME_BARE_WILDCARD_PEM: &[u8] =
    include_bytes!("../../../testdata/cabf_br_dnsname_bare_wildcard.pem");
const OU_PRESENT_PEM: &[u8] = include_bytes!("../../../testdata/cabf_br_ou_present.pem");
const CN_RESERVED_IP_PEM: &[u8] = include_bytes!("../../../testdata/cabf_br_cn_reserved_ip.pem");
const TWO_COMMON_NAMES_PEM: &[u8] =
    include_bytes!("../../../testdata/cabf_br_two_common_names.pem");
const COUNTRY_NOT_ISO_PEM: &[u8] = include_bytes!("../../../testdata/cabf_br_country_not_iso.pem");

// Feature 17 depth-expansion BR fixtures (each a BR-compliant leaf EXCEPT its one
// NEW target, modulo the two documented intentional co-fires; generated by
// testdata/generate.sh). Every NON-good leaf below additionally emits a
// `cabf_br_certificate_policies_present` Warn because it carries no
// CertificatePolicies extension — that additive Warn never breaks an Error-keyed
// isolation assertion (good.pem is the only leaf carrying a policy OID).
const KU_CERT_SIGN_PEM: &[u8] = include_bytes!("../../../testdata/cabf_br_ku_cert_sign.pem");
const KU_CRL_SIGN_PEM: &[u8] = include_bytes!("../../../testdata/cabf_br_ku_crl_sign.pem");
const LEAF_PATH_LEN_PEM: &[u8] = include_bytes!("../../../testdata/cabf_br_leaf_path_len.pem");
const EKU_ANY_PEM: &[u8] = include_bytes!("../../../testdata/cabf_br_eku_any.pem");
const EKU_NO_SERVER_AUTH_PEM: &[u8] =
    include_bytes!("../../../testdata/cabf_br_eku_no_server_auth.pem");
const SAN_EMAIL_ENTRY_PEM: &[u8] = include_bytes!("../../../testdata/cabf_br_san_email_entry.pem");
const NO_SAN_PEM: &[u8] = include_bytes!("../../../testdata/cabf_br_no_san.pem");
const NO_POLICIES_PEM: &[u8] = include_bytes!("../../../testdata/cabf_br_no_policies.pem");
const POLICIES_NO_RESERVED_PEM: &[u8] =
    include_bytes!("../../../testdata/cabf_br_policies_no_reserved.pem");
const RSA_MOD_NOT_OCT_PEM: &[u8] = include_bytes!("../../../testdata/cabf_br_rsa_mod_not_oct.pem");
const RSA_EXP_3_PEM: &[u8] = include_bytes!("../../../testdata/cabf_br_rsa_exp_3.pem");
const NO_BASIC_CONSTRAINTS_PEM: &[u8] =
    include_bytes!("../../../testdata/cabf_br_no_basic_constraints.pem");

/// Loads the single leaf certificate from a PEM fixture; `unwrap` surfaces the
/// `CertError` if the fixture is malformed.
fn load_leaf(pem: &[u8]) -> Cert {
    let mut certs = Cert::load(pem).unwrap();
    certs.remove(0)
}

/// Asserts `findings` contains at least one `Error` whose message contains
/// `needle`.
fn assert_error_mentions(findings: &[linter::Finding], needle: &str) {
    assert!(
        findings.iter().any(|f| f.severity == Severity::Error),
        "expected at least one Error finding, got {findings:?}"
    );
    assert!(
        findings
            .iter()
            .any(|f| f.severity == Severity::Error && f.message.contains(needle)),
        "no Error finding mentioned {needle:?}; findings were {findings:?}"
    );
}

/// Asserts `findings` contains at least one `Warn` (and no `Error`) whose message
/// contains `needle`. Used for the three feature-17 `Warn`-severity BR lints.
fn assert_warn_mentions(findings: &[linter::Finding], needle: &str) {
    assert!(
        !findings.iter().any(|f| f.severity >= Severity::Error),
        "expected no Error/Fatal finding, got {findings:?}"
    );
    assert!(
        findings
            .iter()
            .any(|f| f.severity == Severity::Warn && f.message.contains(needle)),
        "no Warn finding mentioned {needle:?}; findings were {findings:?}"
    );
}

mod validity_max_398_days {
    use super::*;

    #[test]
    fn flags_400_day_leaf_and_names_the_duration() {
        // Setup: a currently-valid leaf with a 400-day window (> 398).
        let cert = load_leaf(VALIDITY_400_PEM);
        let lint = ValidityMax398Days::new();

        // Precondition: in scope (a non-CA leaf).
        assert_eq!(lint.applies(&cert), Applicability::Applies);

        // Invoke.
        let findings = lint.check(&cert);

        // Find + Expect: one Error naming the actual duration and the 398 limit.
        assert_error_mentions(&findings, "400");
        assert_error_mentions(&findings, "398");
    }

    #[test]
    fn passes_for_good_365_day_leaf_at_the_boundary() {
        // good.pem is 365 days (well within 398) — the rule must stay silent.
        let cert = load_leaf(GOOD_PEM);

        let findings = ValidityMax398Days::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca_certificate() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            ValidityMax398Days::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod cn_in_san {
    use super::*;

    #[test]
    fn flags_cn_absent_from_san_and_names_it() {
        // Setup: CN=cn-missing.example.com but SAN lists only other.example.com.
        let cert = load_leaf(CN_NOT_IN_SAN_PEM);
        let lint = CnInSan::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        // Invoke.
        let findings = lint.check(&cert);

        // Find + Expect: one Error naming the offending CN.
        assert_error_mentions(&findings, "cn-missing.example.com");
    }

    #[test]
    fn passes_when_cn_present_in_san() {
        // good.pem: CN == the sole SAN dNSName, so the rule stays silent.
        let cert = load_leaf(GOOD_PEM);

        let findings = CnInSan::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn silent_when_subject_has_no_common_name() {
        // The empty-subject fixture has no CN, so there is nothing to require:
        // the rule emits no finding (it applies, but yields nothing).
        let cert = load_leaf(EMPTY_SUBJECT_NO_SAN_PEM);
        let lint = CnInSan::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);

        assert!(
            findings.is_empty(),
            "a subject with no CN must not trip cn_in_san; got {findings:?}"
        );
    }

    #[test]
    fn not_applicable_on_ca_certificate() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(CnInSan::new().applies(&cert), Applicability::NotApplicable);
    }
}

mod no_internal_names_or_reserved_ip {
    use super::*;

    #[test]
    fn flags_internal_name_and_reserved_ip_with_multiple_findings() {
        // Setup: a leaf whose SAN carries a public name (= CN, so cn_in_san is
        // quiet) PLUS internal.local AND 10.0.0.1 — two offending entries.
        let cert = load_leaf(INTERNAL_SAN_PEM);
        let lint = NoInternalNamesOrReservedIp::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        // Invoke.
        let findings = lint.check(&cert);

        // Find + Expect: one finding per offending entry (two), naming each.
        assert_eq!(
            findings.len(),
            2,
            "expected one finding per offending SAN entry; got {findings:?}"
        );
        assert!(findings.iter().all(|f| f.severity == Severity::Error));
        assert_error_mentions(&findings, "internal.local");
        assert_error_mentions(&findings, "10.0.0.1");
    }

    #[test]
    fn passes_for_good_public_san() {
        // good.pem has only a public dNSName, so the rule stays silent.
        let cert = load_leaf(GOOD_PEM);

        let findings = NoInternalNamesOrReservedIp::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca_certificate() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            NoInternalNamesOrReservedIp::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod ext_key_usage_server_auth_present {
    use super::*;

    #[test]
    fn flags_leaf_without_server_auth() {
        // Setup: a leaf whose EKU carries clientAuth only (no serverAuth).
        let cert = load_leaf(MISSING_SERVERAUTH_PEM);
        let lint = ExtKeyUsageServerAuthPresent::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        // Invoke.
        let findings = lint.check(&cert);

        // Find + Expect: one Error naming the missing serverAuth EKU.
        assert_error_mentions(&findings, "serverAuth");
    }

    #[test]
    fn passes_for_good_leaf_with_server_auth() {
        // good.pem asserts serverAuth, so the rule stays silent.
        let cert = load_leaf(GOOD_PEM);

        let findings = ExtKeyUsageServerAuthPresent::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca_certificate() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            ExtKeyUsageServerAuthPresent::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod ca_scoping {
    use super::*;

    /// All four BR lints must report `NotApplicable` for a CA certificate —
    /// the load-bearing broad-scoping invariant (CA => out of BR scope).
    #[test]
    fn all_four_br_lints_not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            ValidityMax398Days::new().applies(&cert),
            Applicability::NotApplicable
        );
        assert_eq!(CnInSan::new().applies(&cert), Applicability::NotApplicable);
        assert_eq!(
            NoInternalNamesOrReservedIp::new().applies(&cert),
            Applicability::NotApplicable
        );
        assert_eq!(
            ExtKeyUsageServerAuthPresent::new().applies(&cert),
            Applicability::NotApplicable
        );
    }

    /// The dual of the CA invariant: all four BR lints must report `Applies`
    /// for a single non-CA leaf — confirming broad scoping is uniform and NOT
    /// EKU-gated (the leaf is in scope for all four regardless of its EKU).
    #[test]
    fn all_four_br_lints_apply_on_a_non_ca_leaf() {
        let cert = load_leaf(GOOD_PEM);

        assert_eq!(
            ValidityMax398Days::new().applies(&cert),
            Applicability::Applies
        );
        assert_eq!(CnInSan::new().applies(&cert), Applicability::Applies);
        assert_eq!(
            NoInternalNamesOrReservedIp::new().applies(&cert),
            Applicability::Applies
        );
        assert_eq!(
            ExtKeyUsageServerAuthPresent::new().applies(&cert),
            Applicability::Applies
        );
    }
}

// ===========================================================================
// Feature 12: CA/Browser Forum BR depth-expansion lints
// ===========================================================================

mod dnsname_underscore_in_sld {
    use super::*;

    #[test]
    fn flags_underscore_in_san_dns_name() {
        // Setup: SAN with a compliant name plus DNS:foo_bar.example.com.
        let cert = load_leaf(DNSNAME_UNDERSCORE_PEM);
        let lint = DnsnameUnderscoreInSld::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "foo_bar.example.com");
        assert_error_mentions(&findings, "underscore");
    }

    #[test]
    fn passes_for_good_leaf() {
        let cert = load_leaf(GOOD_PEM);

        let findings = DnsnameUnderscoreInSld::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            DnsnameUnderscoreInSld::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod dnsname_bad_character_in_label {
    use super::*;

    #[test]
    fn flags_non_ldh_character_in_san_dns_name() {
        // Setup: SAN with a compliant name plus DNS:foo!bar.example.com.
        let cert = load_leaf(DNSNAME_BAD_CHAR_PEM);
        let lint = DnsnameBadCharacterInLabel::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "foo!bar.example.com");
    }

    #[test]
    fn flags_underscore_too_because_it_is_non_ldh() {
        // The underscore fixture's bad name is ALSO non-LDH, so this lint flags
        // it as well — confirming the inherent overlap with the underscore lint.
        let cert = load_leaf(DNSNAME_UNDERSCORE_PEM);

        let findings = DnsnameBadCharacterInLabel::new().check(&cert);

        assert_error_mentions(&findings, "foo_bar.example.com");
    }

    #[test]
    fn passes_for_good_leaf() {
        let cert = load_leaf(GOOD_PEM);

        let findings = DnsnameBadCharacterInLabel::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            DnsnameBadCharacterInLabel::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod dnsname_label_too_long {
    use super::*;

    #[test]
    fn flags_label_over_63_octets() {
        // Setup: SAN with a compliant name plus a 64-octet label.
        let cert = load_leaf(DNSNAME_LABEL_TOO_LONG_PEM);
        let lint = DnsnameLabelTooLong::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "63");
    }

    #[test]
    fn passes_for_good_leaf_with_short_labels() {
        // good.pem's labels are all < 64 octets (boundary: 63 passes, 64 fails).
        let cert = load_leaf(GOOD_PEM);

        let findings = DnsnameLabelTooLong::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            DnsnameLabelTooLong::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod dnsname_wildcard_left_of_public_suffix {
    use super::*;

    #[test]
    fn flags_bare_wildcard() {
        // Setup: SAN with a compliant name plus the bare wildcard DNS:*.com.
        let cert = load_leaf(DNSNAME_BARE_WILDCARD_PEM);
        let lint = DnsnameWildcardLeftOfPublicSuffix::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "*.com");
    }

    #[test]
    fn does_not_flag_multi_label_wildcard_on_good_leaf() {
        // good.pem is not a wildcard at all; the conservative rule never flags
        // multi-label wildcards like `*.example.com` (covered by the lint's own
        // in-file unit test). Here we confirm the lint stays silent on good.pem.
        let cert = load_leaf(GOOD_PEM);

        let findings = DnsnameWildcardLeftOfPublicSuffix::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            DnsnameWildcardLeftOfPublicSuffix::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod organizational_unit_name_prohibited {
    use super::*;

    #[test]
    fn flags_subject_with_ou() {
        // Setup: a leaf whose subject carries an organizationalUnitName.
        let cert = load_leaf(OU_PRESENT_PEM);
        let lint = OrganizationalUnitNameProhibited::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "organizationalUnitName");
    }

    #[test]
    fn passes_for_good_leaf_without_ou() {
        let cert = load_leaf(GOOD_PEM);

        let findings = OrganizationalUnitNameProhibited::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            OrganizationalUnitNameProhibited::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod subject_contains_reserved_ip {
    use super::*;

    #[test]
    fn flags_reserved_ip_in_common_name() {
        // Setup: subject CN is the reserved IP 10.0.0.1.
        let cert = load_leaf(CN_RESERVED_IP_PEM);
        let lint = SubjectContainsReservedIp::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "10.0.0.1");
    }

    #[test]
    fn passes_for_good_leaf_with_dns_common_name() {
        // good.pem's CN is a DNS name, not an IP — the rule stays silent.
        let cert = load_leaf(GOOD_PEM);

        let findings = SubjectContainsReservedIp::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            SubjectContainsReservedIp::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod extra_subject_common_names {
    use super::*;

    #[test]
    fn flags_two_common_names_and_names_the_count() {
        // Setup: subject carries two commonName attributes.
        let cert = load_leaf(TWO_COMMON_NAMES_PEM);
        let lint = ExtraSubjectCommonNames::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        // The message names the count (2).
        assert_error_mentions(&findings, "2 commonName");
    }

    #[test]
    fn passes_for_good_leaf_with_single_cn() {
        let cert = load_leaf(GOOD_PEM);

        let findings = ExtraSubjectCommonNames::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            ExtraSubjectCommonNames::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod subject_country_not_iso {
    use super::*;

    #[test]
    fn flags_non_iso_country_code() {
        // Setup: subject countryName is "ZZ" (valid length, unassigned code).
        let cert = load_leaf(COUNTRY_NOT_ISO_PEM);
        let lint = SubjectCountryNotIso::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "ZZ");
    }

    #[test]
    fn silent_when_no_country_attribute() {
        // good.pem has no countryName attribute — the lint applies (broad scope)
        // but yields no finding.
        let cert = load_leaf(GOOD_PEM);
        let lint = SubjectCountryNotIso::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert!(
            findings.is_empty(),
            "a cert with no country attribute must stay silent; got {findings:?}"
        );
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            SubjectCountryNotIso::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod new_br_lints_ca_scoping {
    use super::*;

    /// All eight NEW BR lints must report `NotApplicable` for a CA certificate —
    /// the load-bearing broad-scoping invariant extended to the depth lints.
    #[test]
    fn all_eight_new_br_lints_not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        let na = Applicability::NotApplicable;
        assert_eq!(DnsnameUnderscoreInSld::new().applies(&cert), na);
        assert_eq!(DnsnameBadCharacterInLabel::new().applies(&cert), na);
        assert_eq!(DnsnameLabelTooLong::new().applies(&cert), na);
        assert_eq!(DnsnameWildcardLeftOfPublicSuffix::new().applies(&cert), na);
        assert_eq!(OrganizationalUnitNameProhibited::new().applies(&cert), na);
        assert_eq!(SubjectContainsReservedIp::new().applies(&cert), na);
        assert_eq!(ExtraSubjectCommonNames::new().applies(&cert), na);
        assert_eq!(SubjectCountryNotIso::new().applies(&cert), na);
    }
}

// ===========================================================================
// Feature 17: CA/Browser Forum BR depth-expansion lints (12 new)
// ===========================================================================

mod subscriber_key_usage_cert_sign_prohibited {
    use super::*;

    #[test]
    fn flags_leaf_asserting_key_cert_sign() {
        let cert = load_leaf(KU_CERT_SIGN_PEM);
        let lint = SubscriberKeyUsageCertSignProhibited::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "keyCertSign");
    }

    #[test]
    fn passes_for_good_leaf_without_key_usage() {
        let cert = load_leaf(GOOD_PEM);

        let findings = SubscriberKeyUsageCertSignProhibited::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            SubscriberKeyUsageCertSignProhibited::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod subscriber_key_usage_crl_sign_prohibited {
    use super::*;

    #[test]
    fn flags_leaf_asserting_crl_sign() {
        let cert = load_leaf(KU_CRL_SIGN_PEM);
        let lint = SubscriberKeyUsageCrlSignProhibited::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "cRLSign");
    }

    #[test]
    fn passes_for_good_leaf_without_key_usage() {
        let cert = load_leaf(GOOD_PEM);

        let findings = SubscriberKeyUsageCrlSignProhibited::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            SubscriberKeyUsageCrlSignProhibited::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod subscriber_basic_constraints_path_len_prohibited {
    use super::*;

    #[test]
    fn flags_leaf_with_path_len_constraint() {
        let cert = load_leaf(LEAF_PATH_LEN_PEM);
        let lint = SubscriberBasicConstraintsPathLenProhibited::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "pathLenConstraint");
    }

    #[test]
    fn passes_for_good_leaf_without_path_len() {
        let cert = load_leaf(GOOD_PEM);

        let findings = SubscriberBasicConstraintsPathLenProhibited::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            SubscriberBasicConstraintsPathLenProhibited::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod ext_key_usage_any_prohibited {
    use super::*;

    #[test]
    fn flags_any_extended_key_usage() {
        let cert = load_leaf(EKU_ANY_PEM);
        let lint = ExtKeyUsageAnyProhibited::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        // The any-EKU OID is 2.5.29.37.0.
        assert_error_mentions(&findings, "2.5.29.37.0");
    }

    #[test]
    fn passes_for_good_leaf_with_server_auth_only() {
        let cert = load_leaf(GOOD_PEM);

        let findings = ExtKeyUsageAnyProhibited::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            ExtKeyUsageAnyProhibited::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod ext_key_usage_server_auth_required {
    use super::*;

    #[test]
    fn flags_eku_present_without_server_auth() {
        // EKU = clientAuth only (present, no serverAuth).
        let cert = load_leaf(EKU_NO_SERVER_AUTH_PEM);
        let lint = ExtKeyUsageServerAuthRequired::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "serverAuth");
    }

    #[test]
    fn passes_for_good_leaf_with_server_auth() {
        let cert = load_leaf(GOOD_PEM);

        let findings = ExtKeyUsageServerAuthRequired::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn silent_when_eku_absent() {
        // The no-SAN fixture carries an EKU with serverAuth, so it passes; the
        // distinct "EKU absent ⇒ no finding" surface is covered by the lint's own
        // in-file unit test. Here good.pem (EKU present, serverAuth) confirms the
        // pass path; ext_key_usage_server_auth_present (the existing lint) owns the
        // absent-EKU case. This test asserts the new lint stays silent on a leaf
        // whose EKU DOES include serverAuth (good.pem already covers this) — kept
        // as the explicit pass dual.
        let cert = load_leaf(GOOD_PEM);
        let lint = ExtKeyUsageServerAuthRequired::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);
        assert!(lint.check(&cert).is_empty());
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            ExtKeyUsageServerAuthRequired::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod san_dns_or_ip_only {
    use super::*;

    #[test]
    fn flags_each_prohibited_entry_with_multiple_findings() {
        // SAN = DNS:<cn> + email:a@example.com + URI:https://san.example.com/ —
        // two prohibited (non-DNS/IP) entries, so the lint yields TWO findings (one
        // per offending entry). The compliant DNS:<cn> entry is not flagged.
        let cert = load_leaf(SAN_EMAIL_ENTRY_PEM);
        let lint = SanDnsOrIpOnly::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_eq!(
            findings.len(),
            2,
            "expected one finding per offending SAN entry; got {findings:?}"
        );
        assert!(findings.iter().all(|f| f.severity == Severity::Error));
        // Each prohibited entry is named.
        assert_error_mentions(&findings, "a@example.com");
        assert_error_mentions(&findings, "san.example.com");
    }

    #[test]
    fn passes_for_good_leaf_with_single_dns_entry() {
        let cert = load_leaf(GOOD_PEM);

        let findings = SanDnsOrIpOnly::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            SanDnsOrIpOnly::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod san_present {
    use super::*;

    #[test]
    fn warns_when_san_absent() {
        // The no-SAN fixture has a non-empty subject DN but no SAN extension.
        let cert = load_leaf(NO_SAN_PEM);
        let lint = SanPresent::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        // Severity is Warn (not Error) by deliberate cascade design.
        assert_warn_mentions(&findings, "Subject Alternative Name");
    }

    #[test]
    fn passes_for_good_leaf_with_san() {
        let cert = load_leaf(GOOD_PEM);

        let findings = SanPresent::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            SanPresent::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod certificate_policies_present {
    use super::*;

    #[test]
    fn warns_when_policies_absent() {
        let cert = load_leaf(NO_POLICIES_PEM);
        let lint = CertificatePoliciesPresent::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        // Severity is Warn by deliberate cascade design.
        assert_warn_mentions(&findings, "CertificatePolicies");
    }

    #[test]
    fn passes_for_good_leaf_carrying_policies() {
        // good.pem was regenerated to carry a certificatePolicies extension (DV
        // reserved OID 2.23.140.1.2.1), so lint 8 is a POSITIVE pass.
        let cert = load_leaf(GOOD_PEM);

        let findings = CertificatePoliciesPresent::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            CertificatePoliciesPresent::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod certificate_policies_reserved_oid {
    use super::*;

    #[test]
    fn flags_policies_without_a_reserved_oid() {
        // Policies present with a single NON-reserved OID (1.3.6.1.4.1.99999.1).
        let cert = load_leaf(POLICIES_NO_RESERVED_PEM);
        let lint = CertificatePoliciesReservedOid::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "reserved");
    }

    #[test]
    fn passes_for_good_leaf_with_reserved_dv_oid() {
        // good.pem carries the reserved DV OID 2.23.140.1.2.1 — a positive pass.
        let cert = load_leaf(GOOD_PEM);

        let findings = CertificatePoliciesReservedOid::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn silent_when_policies_absent() {
        // The no-policies fixture has no CertificatePolicies extension at all, so
        // this lint (which only fires when policies are PRESENT but none reserved)
        // stays silent.
        let cert = load_leaf(NO_POLICIES_PEM);
        let lint = CertificatePoliciesReservedOid::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);
        assert!(
            lint.check(&cert).is_empty(),
            "reserved-OID lint must stay silent when policies are absent"
        );
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            CertificatePoliciesReservedOid::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod rsa_modulus_bits_multiple_of_8 {
    use super::*;

    #[test]
    fn flags_non_octet_aligned_modulus() {
        let cert = load_leaf(RSA_MOD_NOT_OCT_PEM);
        let lint = RsaModulusBitsMultipleOf8::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "multiple of 8");
    }

    #[test]
    fn passes_for_good_leaf_with_2048_bit_modulus() {
        let cert = load_leaf(GOOD_PEM);

        let findings = RsaModulusBitsMultipleOf8::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            RsaModulusBitsMultipleOf8::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod rsa_public_exponent_in_range {
    use super::*;

    #[test]
    fn flags_small_exponent() {
        // RSA-2048 key with public exponent 3 (< 65537).
        let cert = load_leaf(RSA_EXP_3_PEM);
        let lint = RsaPublicExponentInRange::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "65537");
    }

    #[test]
    fn passes_for_good_leaf_with_exponent_65537() {
        let cert = load_leaf(GOOD_PEM);

        let findings = RsaPublicExponentInRange::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            RsaPublicExponentInRange::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod basic_constraints_present {
    use super::*;

    #[test]
    fn warns_when_basic_constraints_absent() {
        let cert = load_leaf(NO_BASIC_CONSTRAINTS_PEM);
        let lint = BasicConstraintsPresent::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        // Severity is Warn by deliberate cascade design.
        assert_warn_mentions(&findings, "BasicConstraints");
    }

    #[test]
    fn passes_for_good_leaf_with_basic_constraints() {
        let cert = load_leaf(GOOD_PEM);

        let findings = BasicConstraintsPresent::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);

        assert_eq!(
            BasicConstraintsPresent::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod feature_17_lints_ca_scoping {
    use super::*;

    /// All twelve feature-17 BR lints must report `NotApplicable` for a CA
    /// certificate — the load-bearing broad-scoping invariant extended to the new
    /// lints.
    #[test]
    fn all_twelve_new_br_lints_not_applicable_on_ca() {
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);
        let na = Applicability::NotApplicable;

        assert_eq!(
            SubscriberKeyUsageCertSignProhibited::new().applies(&cert),
            na
        );
        assert_eq!(
            SubscriberKeyUsageCrlSignProhibited::new().applies(&cert),
            na
        );
        assert_eq!(
            SubscriberBasicConstraintsPathLenProhibited::new().applies(&cert),
            na
        );
        assert_eq!(ExtKeyUsageAnyProhibited::new().applies(&cert), na);
        assert_eq!(ExtKeyUsageServerAuthRequired::new().applies(&cert), na);
        assert_eq!(SanDnsOrIpOnly::new().applies(&cert), na);
        assert_eq!(SanPresent::new().applies(&cert), na);
        assert_eq!(CertificatePoliciesPresent::new().applies(&cert), na);
        assert_eq!(CertificatePoliciesReservedOid::new().applies(&cert), na);
        assert_eq!(RsaModulusBitsMultipleOf8::new().applies(&cert), na);
        assert_eq!(RsaPublicExponentInRange::new().applies(&cert), na);
        assert_eq!(BasicConstraintsPresent::new().applies(&cert), na);
    }
}

mod default_registry_isolation {
    use super::*;

    /// Each BR fixture, run over the FULL registry, surfaces its single intended
    /// `Error`/`Fatal` violation and no other — proving the fixture isolates
    /// exactly one rule end-to-end across rfc5280 + hygiene + cabf_br. The
    /// per-fixture additive `cabf_br_certificate_policies_present` Warn (every
    /// policies-free leaf gains it) is keyed out by the Error-severity filter.
    ///
    /// NOTE: `cabf_br_missing_serverauth.pem` is DELIBERATELY excluded here — after
    /// feature 17 it co-fires the existing `cabf_br_ext_key_usage_server_auth_present`
    /// AND the new `cabf_br_ext_key_usage_server_auth_required` (its EKU is present
    /// but asserts no serverAuth, which both rules flag). That settled two-rule
    /// reconciliation is asserted in
    /// `missing_serverauth_fixture_trips_both_serverauth_rules`.
    #[test]
    fn each_br_fixture_isolates_exactly_one_violation() {
        // (fixture bytes, the lint_id expected to fire).
        let cases: &[(&[u8], &str)] = &[
            (VALIDITY_400_PEM, "cabf_br_validity_max_398_days"),
            (CN_NOT_IN_SAN_PEM, "cabf_br_cn_in_san"),
            (INTERNAL_SAN_PEM, "cabf_br_no_internal_names_or_reserved_ip"),
        ];

        let registry = default_registry_with_now(Some(TEST_NOW));

        for (pem, expected_lint) in cases {
            let cert = load_leaf(pem);
            let outcomes = registry.run(&cert);

            // The lint_ids of every outcome carrying an Error/Fatal finding.
            let firing: Vec<&str> = outcomes
                .iter()
                .filter(|o| o.findings.iter().any(|f| f.severity >= Severity::Error))
                .map(|o| o.lint_id)
                .collect();

            assert_eq!(
                firing,
                vec![*expected_lint],
                "fixture for {expected_lint} must violate exactly that rule; \
                 firing lints were {firing:?}"
            );
        }
    }

    /// Each NEW (feature 12) BR fixture that CAN be perfectly single-rule, run
    /// over the FULL 32-lint registry, surfaces exactly its one intended
    /// violation and no other Error/Fatal finding. The three fixtures with an
    /// inherent two-rule overlap (underscore, bare-wildcard, cn-reserved-ip) are
    /// excluded here and asserted explicitly below.
    #[test]
    fn each_new_single_rule_br_fixture_isolates_exactly_one_violation() {
        let cases: &[(&[u8], &str)] = &[
            (
                DNSNAME_BAD_CHAR_PEM,
                "cabf_br_dnsname_bad_character_in_label",
            ),
            (DNSNAME_LABEL_TOO_LONG_PEM, "cabf_br_dnsname_label_too_long"),
            (
                OU_PRESENT_PEM,
                "cabf_br_organizational_unit_name_prohibited",
            ),
            (TWO_COMMON_NAMES_PEM, "cabf_br_extra_subject_common_names"),
            (COUNTRY_NOT_ISO_PEM, "cabf_br_subject_country_not_iso"),
        ];

        let registry = default_registry_with_now(Some(TEST_NOW));

        for (pem, expected_lint) in cases {
            let cert = load_leaf(pem);
            let outcomes = registry.run(&cert);

            let firing: Vec<&str> = outcomes
                .iter()
                .filter(|o| o.findings.iter().any(|f| f.severity >= Severity::Error))
                .map(|o| o.lint_id)
                .collect();

            assert_eq!(
                firing,
                vec![*expected_lint],
                "fixture for {expected_lint} must violate exactly that rule; \
                 firing lints were {firing:?}"
            );
        }
    }

    /// Helper: the sorted lint_ids that carry an Error/Fatal finding over the
    /// full registry for `pem`.
    fn firing_error_lints(pem: &[u8]) -> Vec<&'static str> {
        let registry = default_registry_with_now(Some(TEST_NOW));
        let cert = load_leaf(pem);
        let mut firing: Vec<&'static str> = registry
            .run(&cert)
            .into_iter()
            .filter(|o| o.findings.iter().any(|f| f.severity >= Severity::Error))
            .map(|o| o.lint_id)
            .collect();
        firing.sort_unstable();
        firing
    }

    /// `cabf_br_dnsname_underscore.pem` — DOCUMENTED inherent two-rule fixture.
    /// An underscore is also a non-LDH character, so the bad-character lint
    /// co-fires on the same name by construction. There is no underscore name
    /// the LDH check passes, so the overlap is unavoidable; assert the exact pair.
    #[test]
    fn underscore_fixture_trips_underscore_and_bad_character_rules() {
        assert_eq!(
            firing_error_lints(DNSNAME_UNDERSCORE_PEM),
            vec![
                "cabf_br_dnsname_bad_character_in_label",
                "cabf_br_dnsname_underscore_in_sld",
            ]
        );
    }

    /// `cabf_br_dnsname_bare_wildcard.pem` — DOCUMENTED inherent two-rule fixture.
    /// A bare wildcard `*.<tld>` strips to a single-label name (`com`), which
    /// `reserved.rs::is_internal_name` classifies as internal, so the
    /// internal/reserved-name lint co-fires by construction. Assert the pair.
    #[test]
    fn bare_wildcard_fixture_trips_wildcard_and_internal_name_rules() {
        assert_eq!(
            firing_error_lints(DNSNAME_BARE_WILDCARD_PEM),
            vec![
                "cabf_br_dnsname_wildcard_left_of_public_suffix",
                "cabf_br_no_internal_names_or_reserved_ip",
            ]
        );
    }

    /// `cabf_br_cn_reserved_ip.pem` — DOCUMENTED inherent two-rule fixture
    /// (pre-approved in the plan/test-plan). An IP CN must appear in the SAN to
    /// satisfy `cabf_br_cn_in_san`, which trips the existing SAN-reserved-IP lint
    /// too. Chosen approach: accept the two-rule fixture and assert BOTH
    /// reserved-IP rules (CN + SAN) fire, and nothing else. Approach (b) — a
    /// single-rule variant — is impossible because an IP CN cannot be a SAN
    /// dNSName and dropping the SAN IP would instead trip cn_in_san.
    #[test]
    fn cn_reserved_ip_fixture_trips_cn_and_san_reserved_ip_rules() {
        assert_eq!(
            firing_error_lints(CN_RESERVED_IP_PEM),
            vec![
                "cabf_br_no_internal_names_or_reserved_ip",
                "cabf_br_subject_contains_reserved_ip",
            ]
        );
    }

    /// The internal-SAN fixture is the multi-finding case: over the full registry
    /// it produces exactly two Error findings, both from the internal/reserved lint
    /// (one per offending SAN entry) and no other Error. (Like every policies-free
    /// leaf it also carries one additive `cabf_br_certificate_policies_present`
    /// Warn, which is keyed out here — the test is about the two internal/reserved
    /// Errors from a single lint.)
    #[test]
    fn internal_san_fixture_yields_two_error_findings_from_one_lint() {
        let registry = default_registry_with_now(Some(TEST_NOW));
        let cert = load_leaf(INTERNAL_SAN_PEM);

        let outcomes = registry.run(&cert);

        let errors: Vec<(&str, &linter::Finding)> = outcomes
            .iter()
            .flat_map(|o| o.findings.iter().map(move |f| (o.lint_id, f)))
            .filter(|(_, f)| f.severity >= Severity::Error)
            .collect();

        assert_eq!(
            errors.len(),
            2,
            "internal SAN fixture must surface exactly two Error findings; got {errors:?}"
        );
        assert!(
            errors
                .iter()
                .all(|(id, _)| *id == "cabf_br_no_internal_names_or_reserved_ip"),
            "all Error findings must come from the internal/reserved lint; got {errors:?}"
        );

        // The only additive non-Error finding is the BR policies Warn.
        let warns: Vec<&str> = outcomes
            .iter()
            .flat_map(|o| o.findings.iter().map(move |f| (o.lint_id, f)))
            .filter(|(_, f)| f.severity == Severity::Warn)
            .map(|(id, _)| id)
            .collect();
        assert_eq!(
            warns,
            vec!["cabf_br_certificate_policies_present"],
            "the only additive Warn should be the BR policies Warn; got {warns:?}"
        );
    }

    // -----------------------------------------------------------------------
    // Feature 17: per-fixture isolation over the FULL 82-lint registry.
    // -----------------------------------------------------------------------

    /// Each feature-17 ERROR-severity fixture that CAN be perfectly single-rule,
    /// run over the FULL 82-lint registry, surfaces exactly its one new Error rule
    /// and no other Error/Fatal. The per-leaf additive `cabf_br_certificate_policies_present`
    /// Warn is keyed out by the Error-severity filter in `firing_error_lints`. The
    /// two documented two-rule fixtures (leaf-path-len, eku-no-server-auth) are
    /// asserted separately below; the three Warn-only fixtures (no-san, no-policies,
    /// no-basic-constraints) are asserted in `feature_17_warn_only_fixtures_*`.
    #[test]
    fn each_new_single_error_rule_fixture_isolates_exactly_one_violation() {
        let cases: &[(&[u8], &str)] = &[
            (
                KU_CERT_SIGN_PEM,
                "cabf_br_subscriber_key_usage_cert_sign_prohibited",
            ),
            (
                KU_CRL_SIGN_PEM,
                "cabf_br_subscriber_key_usage_crl_sign_prohibited",
            ),
            (EKU_ANY_PEM, "cabf_br_ext_key_usage_any_prohibited"),
            (SAN_EMAIL_ENTRY_PEM, "cabf_br_san_dns_or_ip_only"),
            (
                POLICIES_NO_RESERVED_PEM,
                "cabf_br_certificate_policies_reserved_oid",
            ),
            (
                RSA_MOD_NOT_OCT_PEM,
                "cabf_br_rsa_modulus_bits_multiple_of_8",
            ),
            (RSA_EXP_3_PEM, "cabf_br_rsa_public_exponent_in_range"),
        ];

        for (pem, expected_lint) in cases {
            assert_eq!(
                firing_error_lints(pem),
                vec![*expected_lint],
                "fixture for {expected_lint} must violate exactly that rule"
            );
        }
    }

    /// `cabf_br_leaf_path_len.pem` — DOCUMENTED intentional two-rule fixture. A
    /// pathLenConstraint on a CA:FALSE leaf is improper under BOTH the BR source
    /// (`cabf_br_subscriber_basic_constraints_path_len_prohibited`) and the
    /// feature-12 RFC source (`rfc5280_path_len_constraint_improperly_included`),
    /// so they co-fire by construction. Assert the exact pair (Error-keyed).
    #[test]
    fn leaf_path_len_fixture_trips_both_br_and_rfc_path_len_rules() {
        assert_eq!(
            firing_error_lints(LEAF_PATH_LEN_PEM),
            vec![
                "cabf_br_subscriber_basic_constraints_path_len_prohibited",
                "rfc5280_path_len_constraint_improperly_included",
            ]
        );
    }

    /// `cabf_br_eku_no_server_auth.pem` — DOCUMENTED intentional two-rule fixture
    /// (Phase-1.5 decision 2, lint 5 KEPT). An EKU asserting clientAuth only is
    /// PRESENT but carries no serverAuth, which trips BOTH the new
    /// `cabf_br_ext_key_usage_server_auth_required` AND the existing
    /// `cabf_br_ext_key_usage_server_auth_present`. This is lint 5's
    /// single-rule-vs-existing isolating fixture; the existing
    /// `cabf_br_missing_serverauth.pem` test is reconciled to the SAME two-rule
    /// assertion below.
    #[test]
    fn eku_no_server_auth_fixture_trips_both_serverauth_rules() {
        assert_eq!(
            firing_error_lints(EKU_NO_SERVER_AUTH_PEM),
            vec![
                "cabf_br_ext_key_usage_server_auth_present",
                "cabf_br_ext_key_usage_server_auth_required",
            ]
        );
    }

    /// Reconciliation (settled): the existing `cabf_br_missing_serverauth.pem`
    /// (EKU present without serverAuth) now CO-FIRES the existing serverAuth-present
    /// lint AND the feature-17 serverAuth-required lint (lint 5 is KEPT, not cut).
    /// Asserted as the documented two-rule pair, mirroring
    /// `eku_no_server_auth_fixture_trips_both_serverauth_rules`.
    #[test]
    fn missing_serverauth_fixture_trips_both_serverauth_rules() {
        assert_eq!(
            firing_error_lints(MISSING_SERVERAUTH_PEM),
            vec![
                "cabf_br_ext_key_usage_server_auth_present",
                "cabf_br_ext_key_usage_server_auth_required",
            ]
        );
    }

    /// Sorted lint_ids of the outcomes carrying a `Warn` (not Error) finding over
    /// the full registry for `pem`.
    fn firing_warn_lints(pem: &[u8]) -> Vec<&'static str> {
        let registry = default_registry_with_now(Some(TEST_NOW));
        let cert = load_leaf(pem);
        let mut warns: Vec<&'static str> = registry
            .run(&cert)
            .into_iter()
            .filter(|o| {
                o.findings.iter().any(|f| f.severity == Severity::Warn)
                    && !o.findings.iter().any(|f| f.severity >= Severity::Error)
            })
            .map(|o| o.lint_id)
            .collect();
        warns.sort_unstable();
        warns
    }

    /// The three feature-17 `Warn`-only fixtures fire NO Error across the full
    /// registry, and exactly their one target Warn PLUS (for the no-SAN and
    /// no-BasicConstraints leaves, which also lack a policies extension) the
    /// additive `cabf_br_certificate_policies_present` Warn. The no-policies leaf
    /// fires only the single policies Warn.
    #[test]
    fn feature_17_warn_only_fixtures_fire_no_error_and_their_warns() {
        // No-SAN leaf: san_present Warn + the additive policies Warn, no Error.
        assert!(firing_error_lints(NO_SAN_PEM).is_empty());
        assert_eq!(
            firing_warn_lints(NO_SAN_PEM),
            vec![
                "cabf_br_certificate_policies_present",
                "cabf_br_san_present",
            ]
        );

        // No-policies leaf: exactly the single policies Warn, no Error.
        assert!(firing_error_lints(NO_POLICIES_PEM).is_empty());
        assert_eq!(
            firing_warn_lints(NO_POLICIES_PEM),
            vec!["cabf_br_certificate_policies_present"]
        );

        // No-BasicConstraints leaf: basic_constraints_present Warn + the additive
        // policies Warn, no Error.
        assert!(firing_error_lints(NO_BASIC_CONSTRAINTS_PEM).is_empty());
        assert_eq!(
            firing_warn_lints(NO_BASIC_CONSTRAINTS_PEM),
            vec![
                "cabf_br_basic_constraints_present",
                "cabf_br_certificate_policies_present",
            ]
        );
    }

    /// Regression guard: the clean leaf `good.pem` passes the ENTIRE 82-lint
    /// registry with NO finding at all — not just no Error/Fatal, but also no
    /// `Warn`. After the feature-17 regeneration good.pem carries a
    /// certificatePolicies extension with the reserved DV OID, so lints 8 and 9
    /// (certificate_policies_present + certificate_policies_reserved_oid) are
    /// POSITIVE passes and emit no Warn. good.pem is completely finding-free.
    #[test]
    fn good_pem_yields_no_finding_at_all() {
        let registry = default_registry_with_now(Some(TEST_NOW));
        let cert = load_leaf(GOOD_PEM);

        let outcomes = registry.run(&cert);

        let any: Vec<_> = outcomes
            .iter()
            .flat_map(|o| o.findings.iter().map(move |f| (o.lint_id, f)))
            .collect();
        assert!(
            any.is_empty(),
            "good.pem must be completely finding-free (no Error AND no Warn), but found: {any:?}"
        );
    }

    /// Explicit documentation of the good.pem regeneration: good.pem PASSES the two
    /// CertificatePolicies lints (8 and 9) directly through the lint API — lint 8
    /// because the certificatePolicies extension is present, lint 9 because it
    /// carries the reserved DV OID 2.23.140.1.2.1. Asserted at the lint level so
    /// the regeneration is documented, not silent.
    #[test]
    fn good_pem_passes_certificate_policies_lints_8_and_9() {
        let cert = load_leaf(GOOD_PEM);

        assert!(
            CertificatePoliciesPresent::new().check(&cert).is_empty(),
            "lint 8 must pass on good.pem (policies present)"
        );
        assert!(
            CertificatePoliciesReservedOid::new()
                .check(&cert)
                .is_empty(),
            "lint 9 must pass on good.pem (reserved DV OID present)"
        );
    }
}
