//! Integration tests for the six RFC 5280 structural lints.
//!
//! Each lint owns a dedicated fixture under `testdata/` that violates EXACTLY
//! that rule and passes every other RFC 5280 lint (and `not_expired`, via a
//! far-future `notAfter`). These tests load the real committed fixtures through
//! the public `Cert` facade, construct each lint directly, and assert:
//!
//! - the violating fixture yields at least one `Error` finding with a message
//!   substring tying it to the rule;
//! - `good.pem` (a clean leaf) produces no findings, or `NotApplicable` for the
//!   lints scoped out of a non-CA / non-empty-subject leaf;
//! - the CA-only lints report `NotApplicable` on the leaf, and
//!   `san_present_if_subject_empty` reports `NotApplicable` when the subject is
//!   populated;
//! - the full `default_registry()` over `good.pem` yields no `Error`/`Fatal`
//!   findings.
//!
//! Conventions (`.claude/rules/rust-testing-core.md`): SIFER, nested module per
//! lint, `.unwrap()`/`.unwrap_err()`-style result assertions.
//!
//! # Note on feature 05 (CA/Browser Forum BR lints)
//!
//! The default registry now also contains the four broad-scoped `cabf_br_*`
//! lints, so `default_registry()` runs 14 lints (4 hygiene + 6 rfc5280 +
//! 4 cabf_br). To keep the isolation tests below valid, every non-CA leaf
//! fixture was regenerated BR-compliant-except-its-target: each carries a
//! `serverAuth` EKU, a SAN whose dNSName equals the subject CN (a public
//! `*.example.com` name — `.example` itself is a *reserved* suffix), and a
//! currently-valid `<=398d` window (`2026-06-01 -> 2027-06-01`). That is why the
//! fixtures now carry SAN/EKU. The assertion logic here is UNCHANGED.
//!
//! ⚠️ Time-fragility: those leaves EXPIRE on 2027-06-01; after that
//! `hygiene_not_expired` fires on every leaf and these tests fail wholesale.
//! Regenerate `testdata/` annually (see `testdata/generate.sh`).

use linter::lints::rfc5280::{
    BasicConstraintsCriticalOnCa, CaSubjectFieldEmpty, ExtAuthorityKeyIdentifierNoKeyIdentifier,
    ExtKeyUsageWithoutBits, ExtNameConstraintsNotCritical, ExtSanNoEntries,
    ExtSubjectKeyIdentifierMissingCa, ExtSubjectKeyIdentifierMissingSubCert, KeyUsagePresentWhenCa,
    PathLenConstraintImproperlyIncluded, SanPresentIfSubjectEmpty, SerialNumberPositive,
    SubjectDnCountryNotPrintableString, UtcTimeNotInZulu, ValidityNotAfterAfterNotBefore,
    VersionIsV3,
};
use linter::{Applicability, Cert, Lint, Severity, default_registry_with_now};

/// A reference "now" inside every currently-valid fixture window (2026-12-01 in
/// Unix seconds), used to pin the clock for full-registry runs that include the
/// hygiene source so `hygiene_not_expired` cannot trip once the real date passes
/// the fixtures' `notAfter` (all these leaves expire 2027-06-01).
const TEST_NOW: i64 = 1_796_083_200;

// `include_bytes!` resolves relative to this source file
// (crates/linter/tests/rfc5280.rs); `../../../testdata` reaches the
// workspace-root `testdata/` directory.
const GOOD_PEM: &[u8] = include_bytes!("../../../testdata/good.pem");
const VERSION_NOT_V3_PEM: &[u8] = include_bytes!("../../../testdata/rfc5280_version_not_v3.pem");
const SERIAL_ZERO_PEM: &[u8] = include_bytes!("../../../testdata/rfc5280_serial_number_zero.pem");
const VALIDITY_INVERTED_PEM: &[u8] =
    include_bytes!("../../../testdata/rfc5280_validity_inverted.pem");
const CA_BC_NOT_CRITICAL_PEM: &[u8] =
    include_bytes!("../../../testdata/rfc5280_ca_bc_not_critical.pem");
const CA_MISSING_KEYCERTSIGN_PEM: &[u8] =
    include_bytes!("../../../testdata/rfc5280_ca_missing_keycertsign.pem");
const EMPTY_SUBJECT_NO_SAN_PEM: &[u8] =
    include_bytes!("../../../testdata/rfc5280_empty_subject_no_san.pem");

// Feature 12 depth-expansion fixtures (each violates EXACTLY its one new rule
// across the FULL 32-lint registry; generated by testdata/generate.sh).
const CA_SUBJECT_EMPTY_PEM: &[u8] =
    include_bytes!("../../../testdata/rfc5280_ca_subject_empty.pem");
const EKU_EMPTY_PEM: &[u8] = include_bytes!("../../../testdata/rfc5280_eku_empty.pem");
const AKI_NO_KEYID_PEM: &[u8] = include_bytes!("../../../testdata/rfc5280_aki_no_keyid.pem");
const SKI_MISSING_CA_PEM: &[u8] = include_bytes!("../../../testdata/rfc5280_ski_missing_ca.pem");
const SKI_MISSING_SUB_CERT_PEM: &[u8] =
    include_bytes!("../../../testdata/rfc5280_ski_missing_sub_cert.pem");
const PATH_LEN_ON_LEAF_PEM: &[u8] =
    include_bytes!("../../../testdata/rfc5280_path_len_on_leaf.pem");
const NAME_CONSTRAINTS_NOT_CRITICAL_PEM: &[u8] =
    include_bytes!("../../../testdata/rfc5280_name_constraints_not_critical.pem");
const COUNTRY_NOT_PRINTABLE_PEM: &[u8] =
    include_bytes!("../../../testdata/rfc5280_country_not_printable.pem");
const SAN_EMPTY_PEM: &[u8] = include_bytes!("../../../testdata/rfc5280_san_empty.pem");
const UTCTIME_NOT_ZULU_PEM: &[u8] =
    include_bytes!("../../../testdata/rfc5280_utctime_not_zulu.pem");

/// Loads the single leaf certificate from a PEM fixture; `unwrap` surfaces the
/// `CertError` if the fixture is malformed.
fn load_leaf(pem: &[u8]) -> Cert {
    let mut certs = Cert::load(pem).unwrap();
    certs.remove(0)
}

/// Asserts that `findings` contains at least one `Error` whose message contains
/// `needle`, returning a readable panic otherwise.
fn assert_error_mentions(findings: &[linter::Finding], needle: &str) {
    assert!(
        findings.iter().any(|f| f.severity == Severity::Error),
        "expected at least one Error finding, got {findings:?}"
    );
    assert!(
        findings
            .iter()
            .any(|f| f.severity == Severity::Error && f.message.contains(needle)),
        "no Error finding mentioned {needle:?}; findings were {findings:?}"
    );
}

/// Asserts that `findings` contains at least one `Warn` (and no `Error`/`Fatal`)
/// whose message contains `needle` — used for SHOULD-level rules.
fn assert_warn_mentions(findings: &[linter::Finding], needle: &str) {
    assert!(
        findings.iter().all(|f| f.severity < Severity::Error),
        "expected only Warn-or-below findings, got {findings:?}"
    );
    assert!(
        findings
            .iter()
            .any(|f| f.severity == Severity::Warn && f.message.contains(needle)),
        "no Warn finding mentioned {needle:?}; findings were {findings:?}"
    );
}

mod version_is_v3 {
    use super::*;

    #[test]
    fn flags_v1_certificate_that_carries_extensions() {
        // Setup: a cert whose DER version byte was patched to v1 while keeping
        // its extensions TLV — exactly the case the rule forbids.
        let cert = load_leaf(VERSION_NOT_V3_PEM);
        let lint = VersionIsV3::new();

        // Invoke.
        let findings = lint.check(&cert);

        // Find + Expect: one Error tying the failure to the version/extension rule.
        assert_error_mentions(&findings, "extensions");
    }

    #[test]
    fn passes_for_good_leaf() {
        let cert = load_leaf(GOOD_PEM);

        let findings = VersionIsV3::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn applies_to_any_certificate() {
        let cert = load_leaf(GOOD_PEM);

        assert_eq!(VersionIsV3::new().applies(&cert), Applicability::Applies);
    }
}

mod serial_number_positive {
    use super::*;

    #[test]
    fn flags_zero_serial() {
        // Setup: a leaf signed with serial 0.
        let cert = load_leaf(SERIAL_ZERO_PEM);
        let lint = SerialNumberPositive::new();

        // Invoke.
        let findings = lint.check(&cert);

        // Find + Expect.
        assert_error_mentions(&findings, "zero");
    }

    #[test]
    fn passes_for_good_leaf() {
        let cert = load_leaf(GOOD_PEM);

        let findings = SerialNumberPositive::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }

    #[test]
    fn applies_to_any_certificate() {
        let cert = load_leaf(GOOD_PEM);

        assert_eq!(
            SerialNumberPositive::new().applies(&cert),
            Applicability::Applies
        );
    }
}

mod validity_window {
    use super::*;

    #[test]
    fn flags_non_positive_validity_window() {
        // Setup: a leaf whose notAfter == notBefore (an empty window), which the
        // rule forbids (it requires notAfter strictly later than notBefore).
        let cert = load_leaf(VALIDITY_INVERTED_PEM);
        let lint = ValidityNotAfterAfterNotBefore::new();

        // Invoke.
        let findings = lint.check(&cert);

        // Find + Expect.
        assert_error_mentions(&findings, "notAfter");
    }

    #[test]
    fn passes_for_good_leaf() {
        let cert = load_leaf(GOOD_PEM);

        let findings = ValidityNotAfterAfterNotBefore::new().check(&cert);

        assert!(findings.is_empty(), "good.pem must pass; got {findings:?}");
    }
}

mod basic_constraints_critical_on_ca {
    use super::*;

    #[test]
    fn flags_ca_with_non_critical_basic_constraints() {
        // Setup: a CA whose BasicConstraints is NOT marked critical (but whose
        // keyUsage does carry keyCertSign, so only THIS rule is violated).
        let cert = load_leaf(CA_BC_NOT_CRITICAL_PEM);
        let lint = BasicConstraintsCriticalOnCa::new();

        // Precondition: the lint must consider this CA in scope.
        assert_eq!(lint.applies(&cert), Applicability::Applies);

        // Invoke.
        let findings = lint.check(&cert);

        // Find + Expect.
        assert_error_mentions(&findings, "critical");
    }

    #[test]
    fn not_applicable_on_leaf() {
        // A non-CA leaf is out of scope for this CA-only rule.
        let cert = load_leaf(GOOD_PEM);

        assert_eq!(
            BasicConstraintsCriticalOnCa::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod key_usage_present_when_ca {
    use super::*;

    #[test]
    fn flags_ca_missing_key_cert_sign() {
        // Setup: a CA with critical BasicConstraints whose keyUsage lacks the
        // keyCertSign bit — only THIS rule is violated.
        let cert = load_leaf(CA_MISSING_KEYCERTSIGN_PEM);
        let lint = KeyUsagePresentWhenCa::new();

        // Precondition: in scope (it is a CA).
        assert_eq!(lint.applies(&cert), Applicability::Applies);

        // Invoke.
        let findings = lint.check(&cert);

        // Find + Expect.
        assert_error_mentions(&findings, "keyCertSign");
    }

    #[test]
    fn not_applicable_on_leaf() {
        // A non-CA leaf is out of scope for this CA-only rule.
        let cert = load_leaf(GOOD_PEM);

        assert_eq!(
            KeyUsagePresentWhenCa::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod san_present_if_subject_empty {
    use super::*;

    #[test]
    fn flags_empty_subject_without_san() {
        // Setup: a non-CA leaf with an empty subject DN and no SAN — only THIS
        // rule is violated (CA lints are N/A on a non-CA cert).
        let cert = load_leaf(EMPTY_SUBJECT_NO_SAN_PEM);
        let lint = SanPresentIfSubjectEmpty::new();

        // Precondition: in scope (the subject is empty).
        assert_eq!(lint.applies(&cert), Applicability::Applies);

        // Invoke.
        let findings = lint.check(&cert);

        // Find + Expect.
        assert_error_mentions(&findings, "subjectAltName");
    }

    #[test]
    fn not_applicable_when_subject_present() {
        // good.pem has a non-empty subject, so the rule is out of scope.
        let cert = load_leaf(GOOD_PEM);

        assert_eq!(
            SanPresentIfSubjectEmpty::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

// ===========================================================================
// Feature 12: RFC 5280 depth-expansion lints
// ===========================================================================

mod ca_subject_field_empty {
    use super::*;

    #[test]
    fn flags_ca_with_empty_subject() {
        // Setup: a CA cert whose subject DN is empty (the SAN is critical and the
        // CA structural fields are valid, so only THIS rule fires).
        let cert = load_leaf(CA_SUBJECT_EMPTY_PEM);
        let lint = CaSubjectFieldEmpty::new();

        // Precondition: CA-only rule, in scope for a CA.
        assert_eq!(lint.applies(&cert), Applicability::Applies);

        // Invoke + Expect.
        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "empty subject");
    }

    #[test]
    fn not_applicable_on_leaf() {
        // A non-CA leaf is out of scope for this CA-only rule.
        let cert = load_leaf(GOOD_PEM);

        assert_eq!(
            CaSubjectFieldEmpty::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod ext_key_usage_without_bits {
    use super::*;

    #[test]
    fn flags_empty_extended_key_usage() {
        // Setup: a leaf carrying an EKU extension with zero KeyPurposeIds.
        let cert = load_leaf(EKU_EMPTY_PEM);
        let lint = ExtKeyUsageWithoutBits::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "ExtendedKeyUsage");
    }

    #[test]
    fn not_applicable_when_eku_absent() {
        // good.pem has a non-empty EKU — the lint applies and passes there; a
        // fixture WITHOUT any EKU would be NotApplicable. good.pem proves the
        // pass path.
        let cert = load_leaf(GOOD_PEM);

        // good.pem carries serverAuth, so the EKU extension IS present and the
        // lint applies but produces no findings.
        assert_eq!(
            ExtKeyUsageWithoutBits::new().applies(&cert),
            Applicability::Applies
        );
        assert!(ExtKeyUsageWithoutBits::new().check(&cert).is_empty());
    }
}

mod ext_authority_key_identifier_no_key_identifier {
    use super::*;

    #[test]
    fn flags_aki_without_key_identifier() {
        // Setup: a leaf whose AKI carries only issuer+serial, no keyIdentifier.
        let cert = load_leaf(AKI_NO_KEYID_PEM);
        let lint = ExtAuthorityKeyIdentifierNoKeyIdentifier::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "AuthorityKeyIdentifier");
    }

    #[test]
    fn not_applicable_when_aki_absent() {
        // good.pem has no AKI extension — the rule is out of scope.
        let cert = load_leaf(GOOD_PEM);

        assert_eq!(
            ExtAuthorityKeyIdentifierNoKeyIdentifier::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod ext_subject_key_identifier_missing_ca {
    use super::*;

    #[test]
    fn flags_ca_without_subject_key_identifier() {
        // Setup: a CA cert with no SKI extension.
        let cert = load_leaf(SKI_MISSING_CA_PEM);
        let lint = ExtSubjectKeyIdentifierMissingCa::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "SubjectKeyIdentifier");
    }

    #[test]
    fn not_applicable_on_leaf() {
        // good.pem is a non-CA leaf — this CA-only rule is out of scope.
        let cert = load_leaf(GOOD_PEM);

        assert_eq!(
            ExtSubjectKeyIdentifierMissingCa::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod ext_subject_key_identifier_missing_sub_cert {
    use super::*;

    #[test]
    fn warns_for_leaf_without_subject_key_identifier() {
        // Setup: a BR-compliant leaf with no SKI. This is a SHOULD, so the only
        // finding must be a Warn (not an Error).
        let cert = load_leaf(SKI_MISSING_SUB_CERT_PEM);
        let lint = ExtSubjectKeyIdentifierMissingSubCert::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        // Asserts severity == Warn (the SHOULD level), never Error.
        assert_warn_mentions(&findings, "SubjectKeyIdentifier");
    }

    #[test]
    fn not_applicable_on_ca() {
        // The CA-subject-empty fixture is a CA, so this sub-cert (leaf-only) rule
        // is out of scope there.
        let cert = load_leaf(CA_SUBJECT_EMPTY_PEM);

        assert_eq!(
            ExtSubjectKeyIdentifierMissingSubCert::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod path_len_constraint_improperly_included {
    use super::*;

    #[test]
    fn flags_path_len_on_non_ca_leaf() {
        // Setup: a leaf (CA:FALSE) carrying a pathLenConstraint — meaningless
        // outside a keyCertSign CA.
        let cert = load_leaf(PATH_LEN_ON_LEAF_PEM);
        let lint = PathLenConstraintImproperlyIncluded::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "pathLenConstraint");
    }

    #[test]
    fn not_applicable_when_path_len_absent() {
        // good.pem has no pathLenConstraint — the rule is out of scope.
        let cert = load_leaf(GOOD_PEM);

        assert_eq!(
            PathLenConstraintImproperlyIncluded::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod ext_name_constraints_not_critical {
    use super::*;

    #[test]
    fn flags_non_critical_name_constraints() {
        // Setup: a cert with a NameConstraints extension that is not critical.
        let cert = load_leaf(NAME_CONSTRAINTS_NOT_CRITICAL_PEM);
        let lint = ExtNameConstraintsNotCritical::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "NameConstraints");
    }

    #[test]
    fn not_applicable_when_name_constraints_absent() {
        // good.pem has no NameConstraints — the rule is out of scope.
        let cert = load_leaf(GOOD_PEM);

        assert_eq!(
            ExtNameConstraintsNotCritical::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod subject_dn_country_not_printable_string {
    use super::*;

    #[test]
    fn flags_country_encoded_as_utf8_string() {
        // Setup: a leaf whose subject countryName is a UTF8String (tag patched
        // from PrintableString) rather than the RFC-mandated PrintableString.
        let cert = load_leaf(COUNTRY_NOT_PRINTABLE_PEM);
        let lint = SubjectDnCountryNotPrintableString::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "PrintableString");
    }

    #[test]
    fn not_applicable_when_no_country_attribute() {
        // good.pem has no countryName attribute — the rule is out of scope.
        let cert = load_leaf(GOOD_PEM);

        assert_eq!(
            SubjectDnCountryNotPrintableString::new().applies(&cert),
            Applicability::NotApplicable
        );
    }
}

mod ext_san_no_entries {
    use super::*;

    #[test]
    fn flags_san_with_zero_general_names() {
        // Setup: a leaf carrying a SAN extension with zero GeneralNames.
        let cert = load_leaf(SAN_EMPTY_PEM);
        let lint = ExtSanNoEntries::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        assert_error_mentions(&findings, "subjectAltName");
    }

    #[test]
    fn passes_for_good_leaf_with_one_entry() {
        // good.pem has a SAN with one dNSName — the lint applies and passes.
        let cert = load_leaf(GOOD_PEM);

        assert_eq!(
            ExtSanNoEntries::new().applies(&cert),
            Applicability::Applies
        );
        assert!(ExtSanNoEntries::new().check(&cert).is_empty());
    }
}

mod utc_time_not_in_zulu {
    use super::*;

    #[test]
    fn flags_utc_time_in_offset_form() {
        // Setup: a leaf whose notBefore UTCTime is in the "+0000" offset form
        // (not Zulu). RFC 5280 requires the YYMMDDHHMMSSZ Zulu form.
        let cert = load_leaf(UTCTIME_NOT_ZULU_PEM);
        let lint = UtcTimeNotInZulu::new();

        assert_eq!(lint.applies(&cert), Applicability::Applies);

        let findings = lint.check(&cert);
        // notBefore is the offending field.
        assert_error_mentions(&findings, "notBefore");
    }

    #[test]
    fn passes_for_good_leaf_in_zulu() {
        // good.pem's validity is UTCTime ending in Z — the lint applies and
        // passes.
        let cert = load_leaf(GOOD_PEM);

        assert_eq!(
            UtcTimeNotInZulu::new().applies(&cert),
            Applicability::Applies
        );
        assert!(UtcTimeNotInZulu::new().check(&cert).is_empty());
    }
}

mod default_registry_over_good {
    use super::*;

    /// The clean leaf `good.pem` must pass the entire shipped registry: no
    /// finding at `Error` or `Fatal` from any lint (the CA-only lints and the
    /// SAN lint are `NotApplicable`, the structural lints pass).
    #[test]
    fn good_pem_yields_no_error_or_fatal_findings() {
        // Setup.
        let registry = default_registry_with_now(Some(TEST_NOW));
        let cert = load_leaf(GOOD_PEM);

        // Invoke.
        let outcomes = registry.run(&cert);

        // Find + Expect: scan every finding across every outcome.
        let offending: Vec<_> = outcomes
            .iter()
            .flat_map(|o| o.findings.iter().map(move |f| (o.lint_id, f)))
            .filter(|(_, f)| f.severity >= Severity::Error)
            .collect();
        assert!(
            offending.is_empty(),
            "good.pem should pass every lint, but found: {offending:?}"
        );
    }

    /// Each RFC 5280 fixture, run through the FULL registry, must surface its
    /// single intended violation and no other Error/Fatal finding — proving the
    /// fixture isolates exactly one rule end-to-end.
    #[test]
    fn each_fixture_isolates_exactly_one_rfc5280_violation() {
        // (fixture bytes, the lint_id expected to fire).
        let cases: &[(&[u8], &str)] = &[
            (VERSION_NOT_V3_PEM, "rfc5280_version_is_v3"),
            (SERIAL_ZERO_PEM, "rfc5280_serial_number_positive"),
            (
                VALIDITY_INVERTED_PEM,
                "rfc5280_validity_not_after_after_not_before",
            ),
            (
                CA_BC_NOT_CRITICAL_PEM,
                "rfc5280_basic_constraints_critical_on_ca",
            ),
            (
                CA_MISSING_KEYCERTSIGN_PEM,
                "rfc5280_key_usage_present_when_ca",
            ),
            (
                EMPTY_SUBJECT_NO_SAN_PEM,
                "rfc5280_san_present_if_subject_empty",
            ),
        ];

        let registry = default_registry_with_now(Some(TEST_NOW));

        for (pem, expected_lint) in cases {
            let cert = load_leaf(pem);
            let outcomes = registry.run(&cert);

            // The lint_ids of every outcome carrying an Error/Fatal finding.
            let firing: Vec<&str> = outcomes
                .iter()
                .filter(|o| o.findings.iter().any(|f| f.severity >= Severity::Error))
                .map(|o| o.lint_id)
                .collect();

            assert_eq!(
                firing,
                vec![*expected_lint],
                "fixture for {expected_lint} must violate exactly that rule; \
                 firing lints were {firing:?}"
            );
        }
    }

    /// Each NEW (feature 12) RFC 5280 fixture, run over the FULL 32-lint
    /// registry, must surface its single intended violation and no other
    /// Error/Fatal finding — and, since the targets are all rfc5280 rules, no
    /// cabf_br rule may fire. CA-only fixtures additionally have every BR lint
    /// `NotApplicable`.
    #[test]
    fn each_new_rfc5280_fixture_isolates_exactly_one_violation() {
        // NOTE: `rfc5280_eku_empty.pem` is DELIBERATELY excluded from this
        // strict one-rule loop. Its EKU is present but empty, so it carries no
        // serverAuth purpose; under the RAW `default_registry().run()` (which is
        // NOT purpose-gated) the broad-scoped `cabf_br_ext_key_usage_server_auth_present`
        // also fires by construction. The real engine's `CertPurpose::Auto`
        // would resolve this non-serverAuth leaf to `Generic` and never run the
        // BR sources, so this is purely a raw-registry artifact. That fixture's
        // exact two-rule set is asserted separately in
        // `eku_empty_fixture_trips_new_rule_and_br_serverauth_under_raw_registry`.
        //
        // NOTE: `rfc5280_path_len_on_leaf.pem` is ALSO excluded here. A
        // pathLenConstraint on a CA:FALSE leaf is improper under BOTH the RFC
        // source (`rfc5280_path_len_constraint_improperly_included`) AND the
        // feature-17 BR source (`cabf_br_subscriber_basic_constraints_path_len_prohibited`),
        // so the two co-fire by construction. Its exact two-rule set is asserted
        // separately in `path_len_on_leaf_fixture_trips_both_rfc_and_br_rules`.
        let cases: &[(&[u8], &str)] = &[
            (CA_SUBJECT_EMPTY_PEM, "rfc5280_ca_subject_field_empty"),
            (
                AKI_NO_KEYID_PEM,
                "rfc5280_ext_authority_key_identifier_no_key_identifier",
            ),
            (
                SKI_MISSING_CA_PEM,
                "rfc5280_ext_subject_key_identifier_missing_ca",
            ),
            (
                NAME_CONSTRAINTS_NOT_CRITICAL_PEM,
                "rfc5280_ext_name_constraints_not_critical",
            ),
            (
                COUNTRY_NOT_PRINTABLE_PEM,
                "rfc5280_subject_dn_country_not_printable_string",
            ),
            (SAN_EMPTY_PEM, "rfc5280_ext_san_no_entries"),
            (UTCTIME_NOT_ZULU_PEM, "rfc5280_utc_time_not_in_zulu"),
        ];

        let registry = default_registry_with_now(Some(TEST_NOW));

        for (pem, expected_lint) in cases {
            let cert = load_leaf(pem);
            let outcomes = registry.run(&cert);

            // Every outcome carrying an Error/Fatal finding.
            let firing: Vec<&str> = outcomes
                .iter()
                .filter(|o| o.findings.iter().any(|f| f.severity >= Severity::Error))
                .map(|o| o.lint_id)
                .collect();

            assert_eq!(
                firing,
                vec![*expected_lint],
                "fixture for {expected_lint} must violate exactly that rule; \
                 firing lints were {firing:?}"
            );

            // None of the firing lints may be a cabf_br rule.
            assert!(
                !firing.iter().any(|id| id.starts_with("cabf_br_")),
                "rfc5280 fixture for {expected_lint} must not trip any BR rule; \
                 firing lints were {firing:?}"
            );
        }
    }

    /// The empty-EKU fixture's documented multi-rule case under the RAW registry:
    /// it trips the new `rfc5280_ext_key_usage_without_bits` (its target) AND the
    /// two broad-scoped BR serverAuth rules: the existing
    /// `cabf_br_ext_key_usage_server_auth_present` AND the feature-17
    /// `cabf_br_ext_key_usage_server_auth_required` (an empty EKU is PRESENT but
    /// asserts no serverAuth, which both rules flag). No other rule fires. The
    /// purpose-gated engine would resolve this non-serverAuth leaf to `Generic` and
    /// never run the BR sources; this asserts the raw-registry behaviour explicitly
    /// so the overlap is intentional, not silent.
    #[test]
    fn eku_empty_fixture_trips_new_rule_and_br_serverauth_under_raw_registry() {
        let registry = default_registry_with_now(Some(TEST_NOW));
        let cert = load_leaf(EKU_EMPTY_PEM);

        let outcomes = registry.run(&cert);

        let mut firing: Vec<&str> = outcomes
            .iter()
            .filter(|o| o.findings.iter().any(|f| f.severity >= Severity::Error))
            .map(|o| o.lint_id)
            .collect();
        firing.sort_unstable();

        assert_eq!(
            firing,
            vec![
                "cabf_br_ext_key_usage_server_auth_present",
                "cabf_br_ext_key_usage_server_auth_required",
                "rfc5280_ext_key_usage_without_bits",
            ],
            "empty-EKU fixture must trip exactly its new rule plus the two BR \
             serverAuth rules under the raw registry; firing lints were {firing:?}"
        );
    }

    /// `rfc5280_path_len_on_leaf.pem`'s documented two-rule case: a
    /// pathLenConstraint on a CA:FALSE leaf is improper under BOTH the RFC source
    /// (`rfc5280_path_len_constraint_improperly_included`) and the feature-17 BR
    /// source (`cabf_br_subscriber_basic_constraints_path_len_prohibited`), so over
    /// the full registry they co-fire by construction and nothing else fires.
    #[test]
    fn path_len_on_leaf_fixture_trips_both_rfc_and_br_rules() {
        let registry = default_registry_with_now(Some(TEST_NOW));
        let cert = load_leaf(PATH_LEN_ON_LEAF_PEM);

        let outcomes = registry.run(&cert);

        let mut firing: Vec<&str> = outcomes
            .iter()
            .filter(|o| o.findings.iter().any(|f| f.severity >= Severity::Error))
            .map(|o| o.lint_id)
            .collect();
        firing.sort_unstable();

        assert_eq!(
            firing,
            vec![
                "cabf_br_subscriber_basic_constraints_path_len_prohibited",
                "rfc5280_path_len_constraint_improperly_included",
            ],
            "path-len-on-leaf fixture must trip both the RFC and BR path-len rules; \
             firing lints were {firing:?}"
        );
    }

    /// The SKI-missing-sub-cert fixture is a SHOULD: over the FULL registry it
    /// surfaces NO Error/Fatal, and exactly TWO `Warn`s — its target
    /// `rfc5280_ext_subject_key_identifier_missing_sub_cert`, PLUS the feature-17
    /// `cabf_br_certificate_policies_present` (this compliant leaf carries no
    /// CertificatePolicies extension, which the BR Warn-severity lint flags on
    /// every policies-free leaf except the regenerated good.pem). The additive
    /// BR Warn is reconciled here (documented), not hidden.
    #[test]
    fn ski_missing_sub_cert_fixture_yields_only_expected_warns() {
        let registry = default_registry_with_now(Some(TEST_NOW));
        let cert = load_leaf(SKI_MISSING_SUB_CERT_PEM);

        let outcomes = registry.run(&cert);

        // No Error/Fatal anywhere.
        let errors: Vec<_> = outcomes
            .iter()
            .flat_map(|o| o.findings.iter().map(move |f| (o.lint_id, f)))
            .filter(|(_, f)| f.severity >= Severity::Error)
            .collect();
        assert!(
            errors.is_empty(),
            "SKI-missing-sub-cert fixture must produce no Error/Fatal; got {errors:?}"
        );

        // Exactly two Warns: the sub-cert SKI lint (target) and the BR
        // certificate-policies-present lint (additive on every policies-free leaf).
        let mut warns: Vec<&str> = outcomes
            .iter()
            .flat_map(|o| o.findings.iter().map(move |f| (o.lint_id, f)))
            .filter(|(_, f)| f.severity == Severity::Warn)
            .map(|(id, _)| id)
            .collect();
        warns.sort_unstable();
        assert_eq!(
            warns,
            vec![
                "cabf_br_certificate_policies_present",
                "rfc5280_ext_subject_key_identifier_missing_sub_cert",
            ],
            "expected exactly the sub-cert SKI Warn plus the BR policies Warn; \
             got {warns:?}"
        );
    }
}
